name: Automated-bump-version
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  increment-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.merge_commit_sha }}
        fetch-depth: '0'

    - name: Get pull request labels
      id: get_labels
      uses: actions-ecosystem/action-get-latest-pull-request-labels@v1
      with:
          GITHUB_TOKEN: ${{ github.token }}  # Using github.token for read-only access

    - name: Determine version bump type
      id: bump_type
      run: |
        labels=$(echo "${{ steps.get_labels.outputs.labels }}" | tr ',' '\n')
        DEFAULT_BUMP="patch"
        for label in $labels; do
          if [ "$label" == "major" ]; then
            DEFAULT_BUMP="major"
          elif [ "$label" == "minor" ]; then
            DEFAULT_BUMP="minor"
          fi
        done
        echo "::set-output name=DEFAULT_BUMP::$DEFAULT_BUMP"

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: false
        PRERELEASE: true
        DEFAULT_BUMP: ${{ steps.bump_type.outputs.DEFAULT_BUMP }}
