name: Bump version
on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  contents: write
  issues: write

jobs:
  GitVersion:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.merge_commit_sha }}
        fetch-depth: '0'

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.67.0
      env:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: false
        PRERELEASE: true
