name: Automated-bump-version
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  increment-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.merge_commit_sha }}
        fetch-depth: '0'

    - name: Determine version bump type
      id: bump_type
      run: |
          label_name="${{ github.event.label.name }}"
          case $label_name in
            major)
              DEFAULT_BUMP="major"
              ;;
            minor)
              DEFAULT_BUMP="minor"
              ;;
            *)
              DEFAULT_BUMP="patch"
              ;;
          esac
          echo "::set-output name=DEFAULT_BUMP::$DEFAULT_BUMP"

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: false
        PRERELEASE: true
        DEFAULT_BUMP: ${{ steps.bump_type.outputs.DEFAULT_BUMP }}
