- name: Determine version bump type
        id: bump_type
        run: |
          label_name="${{ github.event.label.name }}"
          if [[ -z "$label_name" ]]; then
            DEFAULT_BUMP="patch"  # Default to patch if label_name is empty
          else
            case $label_name in
              major)
                DEFAULT_BUMP="major"
                ;;
              minor)
                DEFAULT_BUMP="minor"
                ;;
              *)
                DEFAULT_BUMP="patch"  # Default to patch for unrecognized labels
                ;;
            esac
          fi
          echo "DEFAULT_BUMP=$DEFAULT_BUMP" >> $GITHUB_ENV
