name: Automated-bump-version
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  increment-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.merge_commit_sha }}
        fetch-depth: '0'
        
    - name: Determine Default Bump
      id: determine-bump
      run: |
       labels=$(jq -r '.pull_request.labels[].name' "${GITHUB_EVENT_PATH}")
         if [[ $labels == *"major"* ]]; then
            echo "major"
          elif [[ $labels == *"patch"* ]]; then
            echo "patch"
          else
            echo "minor"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: false
        PRERELEASE: true
        DEFAULT_BUMP: ${{ steps.determine-bump.outputs.stdout }}
